### ISSUE TITLE
error on index.html

### ISSUE THREAD

**Issue by webmobiles** [leptos-community/start-csr#6]
Caused by:
    unknown <link data-trunk .../> attr value `rel="stylesheet"`; please ensure the value is lowercase and is a supported asset type

file public/style.css exist

index.html call this file and give error/

<!DOCTYPE html>
<html>
  <head>
    
    
    <link data-trunk rel="css" rel="stylesheet" href="public/styles.css" />

    
    <link data-trunk rel="icon" href="public/favicon.ico" />

    
    <link data-trunk rel="rust" data-wasm-opt="z" data-weak-refs />
  </head>
  <body></body>
</html>

**Comment by webmobiles** [comment]
i solved removing  rel="stylesheet"on index.html, please fix the source

**Comment by Narven** [comment]
> i solved removing rel="stylesheet"on index.html, please fix the source

u are my hero... been trying to solve that problem for hours. thanks

**Comment by soundstep** [comment]
@webmobiles same issue, thanks for the solution.

**Comment by tardyp** [comment]
@diversable sorry to ping directly. There is 3 MR on this exact bug, could you please merge it?

**Comment by jpaugh** [comment]
The fix is in #5
